### PR TITLE
Simplified Chinese trsl

### PR DESCRIPTION
**Pull request by ChuijkYahus**

### CODE REVIEW

**Comment by ManaStar** [comment]
Alrighty, so due to an update I've just released this translation is out of date as there are now more entries needed for both woodworks and boatload compat, if you could update this accordingly I'd be more than happy to merge this!

**Comment by ChuijkYahus** [comment]
Would be done by couple of hours from now, or earlier if I've done loading en_us(a bit bad connection).
Thank you so much!

**Comment by ChuijkYahus** [comment]
Seems my phone doesn't let me commit.
Gotta do that 2 hrs later

**Comment by ChuijkYahus** [comment]
> Alrighty, so due to an update I've just released this translation is out of date as there are now more entries needed for both woodworks and boatload compat, if you could update this accordingly I'd be more than happy to merge this!

Done!

**Comment by ManaStar** [comment]
Looks good, thank you for contributing!

**Pull request merged**
